### ISSUE TITLE
Python.h issue

### ISSUE THREAD

**Issue by mst100** [MerosCrypto/mc_bls#3]
`python-dev ` package alone don't resolve Python.h issue but adding also 
`python3-dev `does the job

**Comment by ClashLuke** [comment]
According this [answer](https://askubuntu.com/a/698074) it might also help installing `libpython3-dev`. Thanks to the very detailed description in the apt package manager, we can see that both `libpython3-dev` and `python3-dev` include headers.

>python3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed]
>  header files and a static library for Python (default)
>
>libpython3-dev/bionic-updates,now 3.6.7-1~18.04 amd64 [installed]
>  header files and a static library for Python (default)

A single-line command would look like this: `apt install python3-dev python-dev libpython3-dev `

Whether or not the headers included by llibpython3-dev are new is up for debate, but it might help resolving the issue on some machines.
